### ISSUE TITLE
Ненужная проверка

### ISSUE THREAD

**Issue by DanaZL** [FearGateLP10/lesson2#1]
https://github.com/FearGateLP10/lesson2/blob/035211b720e1c58ec6629a34c1667a8ea38ad1f5/if_age.py#L12

эта строка идет после else на условие, что age <= 6. Это значит, что age уже заведомо больше 6 и левое сравнение в неравенстве не нужно

**Comment by FearGateLP10** [comment]
https://github.com/FearGateLP10/lesson2/commit/b6046f12b280dbaa3dc913f672ff43c1ee5daa34
