### ISSUE TITLE
isinstance вместо type

### ISSUE THREAD

**Issue by DanaZL** [FearGateLP10/lesson2#2]
https://github.com/FearGateLP10/lesson2/blob/035211b720e1c58ec6629a34c1667a8ea38ad1f5/if_str.py#L11

Хорошим тоном является использование функции isinstance() при проверке переменной на принадлежность типу (вместо type())

**Comment by FearGateLP10** [comment]
https://github.com/FearGateLP10/lesson2/commit/b6046f12b280dbaa3dc913f672ff43c1ee5daa34
