### ISSUE TITLE
Неверное сравнение строк

### ISSUE THREAD

**Issue by DanaZL** [FearGateLP10/lesson2#3]
https://github.com/FearGateLP10/lesson2/blob/035211b720e1c58ec6629a34c1667a8ea38ad1f5/if_str.py#L12

Надо проверить, являются ли строки одинаковыми, а коде проверяется одинаковая ли у них длина.

**Comment by FearGateLP10** [comment]
https://github.com/FearGateLP10/lesson2/commit/b6046f12b280dbaa3dc913f672ff43c1ee5daa34
